artist:
  name: Elite Realty LLC
  tagline: Specializing in residential property. Buyers and Sellers.
  seo_title: Elite Realty LLC
  # seo_description:
  # contact_twitter_username: bonniehood
  # contact_phone: 
  # contact_email: bonniehood.elite@gmail.com

social:
  - name: Facebook
    url: https://www.facebook.com/tracyleehomes/

site_language: en
